"""empty message

Revision ID: bd6aa0ef50a5
Revises: f0cc1d5dee04
Create Date: 2025-02-08 20:38:32.630721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6aa0ef50a5'
down_revision = 'f0cc1d5dee04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('login', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('password')
        batch_op.drop_column('login')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
