"""empty message

Revision ID: f0cc1d5dee04
Revises: 
Create Date: 2025-02-06 22:37:47.637356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0cc1d5dee04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainingName', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('muscleGroups', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numberOfTimes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numberOfSets', sa.Integer(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('numberOfSets')
        batch_op.drop_column('numberOfTimes')
        batch_op.drop_column('muscleGroups')
        batch_op.drop_column('trainingName')

    # ### end Alembic commands ###
